services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - ./alembic.ini:/app/alembic.ini

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  alembic:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1111@db:5432/menu_api
    command: >
      sh -c "sleep 5 &&
      alembic upgrade head &&
      tail -f /dev/null"
    volumes:
      - .:/app
      - ./alembic.ini:/app/alembic.ini
volumes:
  postgres_data: