"""Add order_id to dishes

Revision ID: df9b22a25ba3
Revises: a03e31a49596
Create Date: 2025-08-08 23:26:11.308426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9b22a25ba3'
down_revision: Union[str, None] = 'a03e31a49596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dishes', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'order_id')
    # ### end Alembic commands ###
